version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - "27017:27017"

  backend:
    image: tomhoon/deploy-back:latest
    container_name: deploy-back
    restart: always
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://root:pass123@mongodb:27017/mydb?authSource=admin
    ports:
      - "3000:3000"

  frontend:
    image: tomhoon/deploy-front:latest
    container_name: deploy-front
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

volumes:
  mongo_data:
